services:
  - type: web
    name: musicalia-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python avatar_ai_server.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
